struct DepthBudget {
    file: &'static str,
    max_child: usize,
    max_div: usize,
    max_canvas: usize,
    max_chain: usize,
}

fn metrics(src: &str) -> (usize, usize, usize, usize) {
    let mut child = 0usize;
    let mut div = 0usize;
    let mut canvas = 0usize;
    let mut chain = 0usize;
    for line in src.lines() {
        if line.contains(".child(") || line.contains(".children(") {
            child += 1;
        }
        if line.contains("div(") {
            div += 1;
        }
        if line.contains("canvas(") {
            canvas += 1;
        }
        let dots = line.matches('.').count();
        if dots > chain {
            chain = dots;
        }
    }
    (child, div, canvas, chain)
}

const BUDGETS: &[DepthBudget] = &[
    DepthBudget {
        file: "accordion.rs",
        max_child: 13,
        max_div: 6,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "action_icon.rs",
        max_child: 3,
        max_div: 3,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "alert.rs",
        max_child: 15,
        max_div: 11,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "app_shell.rs",
        max_child: 32,
        max_div: 14,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "badge.rs",
        max_child: 5,
        max_div: 3,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "breadcrumbs.rs",
        max_child: 6,
        max_div: 5,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "button.rs",
        max_child: 17,
        max_div: 9,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "checkbox.rs",
        max_child: 15,
        max_div: 8,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "chip.rs",
        max_child: 15,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "control.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "divider.rs",
        max_child: 6,
        max_div: 10,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "drawer.rs",
        max_child: 16,
        max_div: 16,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "field_variant.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "hovercard.rs",
        max_child: 11,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "icon.rs",
        max_child: 3,
        max_div: 3,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "indicator.rs",
        max_child: 6,
        max_div: 13,
        max_canvas: 1,
        max_chain: 7,
    },
    DepthBudget {
        file: "input.rs",
        max_child: 40,
        max_div: 19,
        max_canvas: 2,
        max_chain: 6,
    },
    DepthBudget {
        file: "interaction_adapter.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "layers.rs",
        max_child: 32,
        max_div: 26,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "layout.rs",
        max_child: 9,
        max_div: 10,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "loader.rs",
        max_child: 17,
        max_div: 13,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "loading_overlay.rs",
        max_child: 8,
        max_div: 6,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "markdown.rs",
        max_child: 26,
        max_div: 18,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "menu.rs",
        max_child: 10,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "menu_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "mod.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 2,
    },
    DepthBudget {
        file: "modal.rs",
        max_child: 18,
        max_div: 14,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "number_input.rs",
        max_child: 8,
        max_div: 6,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "overlay.rs",
        max_child: 5,
        max_div: 6,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "pagination.rs",
        max_child: 6,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "paper.rs",
        max_child: 3,
        max_div: 3,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "popover.rs",
        max_child: 6,
        max_div: 3,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "popup.rs",
        max_child: 5,
        max_div: 4,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "popup_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "progress.rs",
        max_child: 13,
        max_div: 8,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "radio.rs",
        max_child: 25,
        max_div: 10,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "range_slider.rs",
        max_child: 34,
        max_div: 16,
        max_canvas: 4,
        max_chain: 6,
    },
    DepthBudget {
        file: "rating.rs",
        max_child: 14,
        max_div: 6,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "scroll_area.rs",
        max_child: 4,
        max_div: 4,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "segmented_control.rs",
        max_child: 17,
        max_div: 11,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "select.rs",
        max_child: 60,
        max_div: 30,
        max_canvas: 2,
        max_chain: 6,
    },
    DepthBudget {
        file: "select_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "selection_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 2,
    },
    DepthBudget {
        file: "slider.rs",
        max_child: 30,
        max_div: 13,
        max_canvas: 2,
        max_chain: 6,
    },
    DepthBudget {
        file: "slider_axis.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "stepper.rs",
        max_child: 25,
        max_div: 11,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "switch.rs",
        max_child: 18,
        max_div: 7,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "table.rs",
        max_child: 42,
        max_div: 18,
        max_canvas: 2,
        max_chain: 4,
    },
    DepthBudget {
        file: "table_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "tabs.rs",
        max_child: 7,
        max_div: 3,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "text.rs",
        max_child: 3,
        max_div: 3,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "text_input_actions.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 2,
    },
    DepthBudget {
        file: "text_input_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "textarea.rs",
        max_child: 33,
        max_div: 16,
        max_canvas: 4,
        max_chain: 6,
    },
    DepthBudget {
        file: "timeline.rs",
        max_child: 17,
        max_div: 8,
        max_canvas: 1,
        max_chain: 6,
    },
    DepthBudget {
        file: "title.rs",
        max_child: 5,
        max_div: 4,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "title_bar.rs",
        max_child: 35,
        max_div: 26,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "toggle.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 3,
    },
    DepthBudget {
        file: "tooltip.rs",
        max_child: 6,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "transition.rs",
        max_child: 2,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "tree.rs",
        max_child: 8,
        max_div: 5,
        max_canvas: 1,
        max_chain: 5,
    },
    DepthBudget {
        file: "tree_state.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
    DepthBudget {
        file: "utils.rs",
        max_child: 2,
        max_div: 2,
        max_canvas: 1,
        max_chain: 4,
    },
];

#[test]
fn component_layout_depth_stays_within_budget() {
    for budget in BUDGETS {
        let src = match budget.file {
            "accordion.rs" => include_str!("../../src/components/accordion.rs"),
            "action_icon.rs" => include_str!("../../src/components/action_icon.rs"),
            "alert.rs" => include_str!("../../src/components/alert.rs"),
            "app_shell.rs" => include_str!("../../src/components/app_shell.rs"),
            "badge.rs" => include_str!("../../src/components/badge.rs"),
            "breadcrumbs.rs" => include_str!("../../src/components/breadcrumbs.rs"),
            "button.rs" => include_str!("../../src/components/button.rs"),
            "checkbox.rs" => include_str!("../../src/components/checkbox.rs"),
            "chip.rs" => include_str!("../../src/components/chip.rs"),
            "control.rs" => include_str!("../../src/components/control.rs"),
            "divider.rs" => include_str!("../../src/components/divider.rs"),
            "drawer.rs" => include_str!("../../src/components/drawer.rs"),
            "field_variant.rs" => include_str!("../../src/components/field_variant.rs"),
            "hovercard.rs" => include_str!("../../src/components/hovercard.rs"),
            "icon.rs" => include_str!("../../src/components/icon.rs"),
            "indicator.rs" => include_str!("../../src/components/indicator.rs"),
            "input.rs" => include_str!("../../src/components/input.rs"),
            "interaction_adapter.rs" => include_str!("../../src/components/interaction_adapter.rs"),
            "layers.rs" => include_str!("../../src/components/layers.rs"),
            "layout.rs" => include_str!("../../src/components/layout.rs"),
            "loader.rs" => include_str!("../../src/components/loader.rs"),
            "loading_overlay.rs" => include_str!("../../src/components/loading_overlay.rs"),
            "markdown.rs" => include_str!("../../src/components/markdown.rs"),
            "menu.rs" => include_str!("../../src/components/menu.rs"),
            "menu_state.rs" => include_str!("../../src/components/menu_state.rs"),
            "mod.rs" => include_str!("../../src/components/mod.rs"),
            "modal.rs" => include_str!("../../src/components/modal.rs"),
            "number_input.rs" => include_str!("../../src/components/number_input.rs"),
            "overlay.rs" => include_str!("../../src/components/overlay.rs"),
            "pagination.rs" => include_str!("../../src/components/pagination.rs"),
            "paper.rs" => include_str!("../../src/components/paper.rs"),
            "popover.rs" => include_str!("../../src/components/popover.rs"),
            "popup.rs" => include_str!("../../src/components/popup.rs"),
            "popup_state.rs" => include_str!("../../src/components/popup_state.rs"),
            "progress.rs" => include_str!("../../src/components/progress.rs"),
            "radio.rs" => include_str!("../../src/components/radio.rs"),
            "range_slider.rs" => include_str!("../../src/components/range_slider.rs"),
            "rating.rs" => include_str!("../../src/components/rating.rs"),
            "scroll_area.rs" => include_str!("../../src/components/scroll_area.rs"),
            "segmented_control.rs" => include_str!("../../src/components/segmented_control.rs"),
            "select.rs" => include_str!("../../src/components/select.rs"),
            "select_state.rs" => include_str!("../../src/components/select_state.rs"),
            "selection_state.rs" => include_str!("../../src/components/selection_state.rs"),
            "slider.rs" => include_str!("../../src/components/slider.rs"),
            "slider_axis.rs" => include_str!("../../src/components/slider_axis.rs"),
            "stepper.rs" => include_str!("../../src/components/stepper.rs"),
            "switch.rs" => include_str!("../../src/components/switch.rs"),
            "table.rs" => include_str!("../../src/components/table.rs"),
            "table_state.rs" => include_str!("../../src/components/table_state.rs"),
            "tabs.rs" => include_str!("../../src/components/tabs.rs"),
            "text.rs" => include_str!("../../src/components/text.rs"),
            "text_input_actions.rs" => include_str!("../../src/components/text_input_actions.rs"),
            "text_input_state.rs" => include_str!("../../src/components/text_input_state.rs"),
            "textarea.rs" => include_str!("../../src/components/textarea.rs"),
            "timeline.rs" => include_str!("../../src/components/timeline.rs"),
            "title.rs" => include_str!("../../src/components/title.rs"),
            "title_bar.rs" => include_str!("../../src/components/title_bar.rs"),
            "toggle.rs" => include_str!("../../src/components/toggle.rs"),
            "tooltip.rs" => include_str!("../../src/components/tooltip.rs"),
            "transition.rs" => include_str!("../../src/components/transition.rs"),
            "tree.rs" => include_str!("../../src/components/tree.rs"),
            "tree_state.rs" => include_str!("../../src/components/tree_state.rs"),
            "utils.rs" => include_str!("../../src/components/utils.rs"),
            _ => unreachable!("unknown component file: {}", budget.file),
        };
        let (child, div, canvas, chain) = metrics(src);
        assert!(
            child <= budget.max_child,
            "{} child_calls {} > {}",
            budget.file,
            child,
            budget.max_child
        );
        assert!(
            div <= budget.max_div,
            "{} div_calls {} > {}",
            budget.file,
            div,
            budget.max_div
        );
        assert!(
            canvas <= budget.max_canvas,
            "{} canvas_calls {} > {}",
            budget.file,
            canvas,
            budget.max_canvas
        );
        assert!(
            chain <= budget.max_chain,
            "{} max_chain {} > {}",
            budget.file,
            chain,
            budget.max_chain
        );
    }
}
